# Generated by Django 3.2 on 2021-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='place_of_birth',
            field=models.TextField(default='Manokwari'),
        ),
    ]
