# Generated by Django 3.2 on 2021-04-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20210428_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hobby',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='place_of_birth',
            field=models.CharField(max_length=30),
        ),
    ]
